version: "3.8"

services:
  app:
    build: .
    container_name: express_app
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    env_file:
      - .env
    environment:
      - MONGO_URL=${MONGO_URL}
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app:cached
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "${FORWARD_REDIS_PORT:-6378}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

volumes:
  mongo_data:
  redis_data:
